Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda1
      Code:
        S3Bucket: my-source-bucket
        S3Key: lambda/my-nodejs-app.zip
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60
      MemorySize: 512
      Environment:
        TestQueue: !GetAtt MyQueue.Arn

  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt MyQueue.Arn
      FunctionName: !GetAtt LambdaFunction.Arn

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: queue1
      DelaySeconds: 0
      VisibilityTimeout: 120